app = 'brunosearch'
primary_region = 'ewr'
swap_size_mb = 512

[build]

[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
auto_stop_machines = "suspend"
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
